# Generated by Django 5.2.9 on 2025-12-22 16:44

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('costing', '0010_billofmaterial_unit_cost_final'),
        ('expenses', '0007_alter_expensebatch_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('allocation_method', models.CharField(choices=[('by_sales_value', 'حسب قيمة المبيعات'), ('by_qty', 'حسب الكمية المباعة')], default='by_sales_value', max_length=30, verbose_name='طريقة توزيع المصروفات')),
                ('notes', models.CharField(blank=True, default='', max_length=255, verbose_name='ملاحظات')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pricing_runs', to='expenses.period', verbose_name='الفترة')),
            ],
            options={
                'verbose_name': 'تشغيل تسعير',
                'verbose_name_plural': 'تشغيلات التسعير',
                'ordering': ('-period__start_date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='PricingLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_sold', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18, verbose_name='الكمية المباعة')),
                ('sales_value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18, verbose_name='قيمة المبيعات')),
                ('avg_price', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='متوسط سعر البيع')),
                ('cogs_total', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18, verbose_name='إجمالي COGS')),
                ('cogs_unit', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name='COGS / وحدة')),
                ('exp_alloc_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18, verbose_name='مصروفات موزعة')),
                ('exp_unit', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name='مصروفات / وحدة')),
                ('full_cost_unit', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name='Full Cost / وحدة')),
                ('profit_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18, verbose_name='ربح إجمالي')),
                ('profit_unit', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name='ربح / وحدة')),
                ('margin_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Margin %')),
                ('suggested_price', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='سعر مقترح')),
                ('target_margin_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='هامش مستهدف %')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='costing.product', verbose_name='المنتج')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='pricing.pricingrun', verbose_name='التشغيل')),
            ],
            options={
                'verbose_name': 'نتيجة تسعير',
                'verbose_name_plural': 'نتائج التسعير',
                'ordering': ('-profit_total',),
                'unique_together': {('run', 'product')},
            },
        ),
    ]
