# Generated by Django 5.2.9 on 2025-12-22 17:26

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costing', '0010_billofmaterial_unit_cost_final'),
        ('expenses', '0007_alter_expensebatch_options'),
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pricing_method', models.CharField(choices=[('margin_percent', 'نسبة ربح %'), ('margin_amount', 'مبلغ ربح ثابت'), ('manual_price', 'سعر بيع يدوي')], default='margin_percent', max_length=20, verbose_name='طريقة التسعير')),
                ('margin_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, verbose_name='نسبة الربح %')),
                ('margin_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='مبلغ الربح')),
                ('manual_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='سعر البيع اليدوي')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.period', verbose_name='الفترة')),
                ('product', models.ForeignKey(limit_choices_to={'is_sellable': True, 'is_semi_finished': False}, on_delete=django.db.models.deletion.CASCADE, to='costing.product', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'سياسة تسعير',
                'verbose_name_plural': 'سياسات التسعير',
                'unique_together': {('product', 'period')},
            },
        ),
        migrations.CreateModel(
            name='PricingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_per_unit', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='تكلفة الوحدة')),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='سعر البيع')),
                ('gross_profit', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='مجمل الربح')),
                ('gross_margin_percent', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='نسبة مجمل الربح %')),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('pricing_policy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='pricing.pricingpolicy')),
            ],
            options={
                'verbose_name': 'نتيجة سياسة التسعير',
                'verbose_name_plural': 'نتائج سياسات التسعير',
            },
        ),
    ]
