# Generated by Django 5.2.3 on 2025-12-23 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costing', '0010_billofmaterial_unit_cost_final'),
        ('expenses', '0007_alter_expensebatch_options'),
        ('pricing', '0002_pricingpolicy_pricingresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direct_cost', models.DecimalField(decimal_places=4, max_digits=14)),
                ('allocated_expense', models.DecimalField(decimal_places=4, max_digits=14)),
                ('full_cost', models.DecimalField(decimal_places=4, max_digits=14)),
                ('sales_qty', models.DecimalField(decimal_places=4, max_digits=14)),
                ('sales_value', models.DecimalField(decimal_places=4, max_digits=14)),
                ('contribution', models.DecimalField(decimal_places=4, max_digits=14)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.period')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='costing.product')),
            ],
        ),
    ]
