# Generated by Django 5.2.9 on 2025-12-05 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('FIXED', 'ثابتة'), ('VARIABLE', 'متغيرة'), ('MIXED', 'مختلطة')], default='FIXED', max_length=10)),
                ('is_accrual', models.BooleanField(default=False, help_text='هل المصروف مستحق (لم يُدفع بعد)؟')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('period_type', models.CharField(choices=[('M', 'شهري'), ('Q', 'ربع سنوي'), ('Y', 'سنوي')], default='M', max_length=1)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExpenseEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('expense_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='expenses.expensetype')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_entries', to='expenses.period')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
