# Generated by Django 5.2.9 on 2025-12-05 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expenseentry',
            options={'verbose_name': 'قيد مصروف', 'verbose_name_plural': 'قيود المصروفات'},
        ),
        migrations.AlterModelOptions(
            name='expensetype',
            options={'verbose_name': 'نوع مصروف', 'verbose_name_plural': 'أنواع المصروفات'},
        ),
        migrations.AlterModelOptions(
            name='period',
            options={'verbose_name': 'فترة', 'verbose_name_plural': 'الفترات'},
        ),
        migrations.AlterField(
            model_name='expenseentry',
            name='amount',
            field=models.DecimalField(decimal_places=4, max_digits=14, verbose_name='المبلغ'),
        ),
        migrations.AlterField(
            model_name='expenseentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='expenseentry',
            name='expense_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='expenses.expensetype', verbose_name='نوع المصروف'),
        ),
        migrations.AlterField(
            model_name='expenseentry',
            name='notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات'),
        ),
        migrations.AlterField(
            model_name='expenseentry',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_entries', to='expenses.period', verbose_name='الفترة'),
        ),
        migrations.AlterField(
            model_name='expenseentry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تعديل'),
        ),
        migrations.AlterField(
            model_name='expensetype',
            name='category',
            field=models.CharField(choices=[('FIXED', 'ثابتة'), ('VARIABLE', 'متغيرة'), ('MIXED', 'مختلطة')], default='FIXED', max_length=10, verbose_name='تصنيف المصروف'),
        ),
        migrations.AlterField(
            model_name='expensetype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='expensetype',
            name='is_accrual',
            field=models.BooleanField(default=False, help_text='هل المصروف مستحق (غير مدفوع)؟', verbose_name='مصروف مستحق'),
        ),
        migrations.AlterField(
            model_name='expensetype',
            name='name',
            field=models.CharField(max_length=200, verbose_name='اسم المصروف'),
        ),
        migrations.AlterField(
            model_name='expensetype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تعديل'),
        ),
        migrations.AlterField(
            model_name='period',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='period',
            name='end_date',
            field=models.DateField(verbose_name='تاريخ النهاية'),
        ),
        migrations.AlterField(
            model_name='period',
            name='name',
            field=models.CharField(max_length=100, verbose_name='اسم الفترة'),
        ),
        migrations.AlterField(
            model_name='period',
            name='period_type',
            field=models.CharField(choices=[('M', 'شهري'), ('Q', 'ربع سنوي'), ('Y', 'سنوي')], default='M', max_length=1, verbose_name='نوع الفترة'),
        ),
        migrations.AlterField(
            model_name='period',
            name='start_date',
            field=models.DateField(verbose_name='تاريخ البداية'),
        ),
        migrations.AlterField(
            model_name='period',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تعديل'),
        ),
    ]
