# Generated by Django 5.2.9 on 2025-12-05 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_alter_expenseentry_options_alter_expensetype_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='period',
            options={'verbose_name': 'فترة', 'verbose_name_plural': 'الفترات'},
        ),

        # ➊ أضف الحقول أولا
        migrations.AddField(
            model_name='period',
            name='year',
            field=models.IntegerField(default=2025, verbose_name='السنة'),
        ),
        migrations.AddField(
            model_name='period',
            name='month',
            field=models.IntegerField(default=1, verbose_name='الشهر (1-12)'),
        ),
        migrations.AddField(
            model_name='period',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='مقفلة؟'),
        ),

        # ➋ بعد إضافة الحقول → عدّل unique_together
        migrations.AlterUniqueTogether(
            name='period',
            unique_together={('year', 'month')},
        ),
    ]
