# Generated by Django 5.2.9 on 2025-12-05 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_alter_period_options_alter_period_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='period',
            options={'ordering': ['year', 'month'], 'verbose_name': 'فترة', 'verbose_name_plural': 'فترات'},
        ),
        migrations.RemoveField(
            model_name='period',
            name='period_type',
        ),
        migrations.AlterField(
            model_name='period',
            name='end_date',
            field=models.DateField(verbose_name='إلى تاريخ'),
        ),
        migrations.AlterField(
            model_name='period',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='اسم الفترة'),
        ),
        migrations.AlterField(
            model_name='period',
            name='start_date',
            field=models.DateField(verbose_name='من تاريخ'),
        ),
        migrations.AlterField(
            model_name='period',
            name='year',
            field=models.IntegerField(choices=[(2024, '2024'), (2025, '2025'), (2026, '2026'), (2027, '2027'), (2028, '2028'), (2029, '2029'), (2030, '2030')], default=2025, verbose_name='السنة'),
        ),
    ]
