# Generated by Django 5.2.9 on 2025-12-22 07:14

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_alter_period_options_remove_period_period_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='الكود')),
                ('name', models.CharField(max_length=200, verbose_name='اسم التصنيف')),
                ('nature', models.CharField(choices=[('OP', 'تشغيلي'), ('SA', 'بيعي'), ('AD', 'إداري')], max_length=2, verbose_name='طبيعة المصروف')),
                ('directness', models.CharField(choices=[('DIRECT', 'مباشر'), ('INDIRECT', 'غير مباشر')], max_length=10, verbose_name='مباشر/غير مباشر')),
                ('frequency', models.CharField(choices=[('MONTHLY', 'شهري'), ('YEARLY', 'سنوي'), ('ADHOC', 'غير دوري')], default='MONTHLY', max_length=10, verbose_name='دورية الصرف')),
                ('behavior', models.CharField(choices=[('FIXED', 'ثابت'), ('VARIABLE', 'متغير')], default='FIXED', max_length=10, verbose_name='ثابت/متغير')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'تصنيف مصروف',
                'verbose_name_plural': 'تصنيفات المصروفات',
                'ordering': ('code',),
            },
        ),
        migrations.AlterModelOptions(
            name='expensetype',
            options={'verbose_name': 'نوع مصروف (قديم)', 'verbose_name_plural': 'أنواع المصروفات (قديمة)'},
        ),
        migrations.CreateModel(
            name='ExpenseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='كود المصروف')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المصروف')),
                ('default_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='مبلغ افتراضي')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='expenses.expensecategory', verbose_name='تصنيف المصروف')),
            ],
            options={
                'verbose_name': 'اسم مصروف',
                'verbose_name_plural': 'أسماء المصروفات',
                'ordering': ('code',),
            },
        ),
    ]
