# Generated by Django 5.2.9 on 2025-12-22 07:32

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_expensecategory_alter_expensetype_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تعديل')),
                ('notes', models.CharField(blank=True, max_length=250, verbose_name='ملاحظات')),
                ('period', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='expenses.period', verbose_name='الفترة')),
            ],
            options={
                'verbose_name': 'مسير مصروفات شهري',
                'verbose_name_plural': 'مسيرات المصروفات الشهرية',
                'ordering': ('-period__year', '-period__month'),
            },
        ),
        migrations.CreateModel(
            name='ExpenseLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='المبلغ')),
                ('notes', models.CharField(blank=True, max_length=250, verbose_name='ملاحظات')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='expenses.expensebatch', verbose_name='المسير')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='expenses.expenseitem', verbose_name='اسم المصروف')),
            ],
            options={
                'verbose_name': 'سطر مصروف',
                'verbose_name_plural': 'سطور المصروفات',
                'ordering': ('item__code',),
                'unique_together': {('batch', 'item')},
            },
        ),
    ]
