# Generated by Django 5.2.9 on 2025-12-22 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_expensebatch_expenseline'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expensebatch',
            options={'verbose_name': 'مصروفات الفترة', 'verbose_name_plural': 'مصروفات الفترات'},
        ),
    ]
