# Generated by Django 5.2.9 on 2025-12-24 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0007_alter_expensebatch_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='allow_opening_stock',
            field=models.BooleanField(default=False, help_text='لا يُفتح جرد أول المدة إلا إذا تم تفعيل هذا الخيار من الفترات.', verbose_name='السماح بفتح جرد أول المدة'),
        ),
        migrations.AddField(
            model_name='period',
            name='inv_opening_enabled',
            field=models.BooleanField(default=False, verbose_name='السماح بفتح جرد أول الفترة'),
        ),
        migrations.AddField(
            model_name='period',
            name='inv_opening_enabled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ فتح جرد أول الفترة'),
        ),
        migrations.AddField(
            model_name='period',
            name='inv_opening_note',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ملاحظة فتح الجرد'),
        ),
        migrations.AddField(
            model_name='period',
            name='inv_opening_once_only',
            field=models.BooleanField(default=True, verbose_name='جرد أول الفترة مرة واحدة فقط'),
        ),
    ]
