# Generated by Django 5.2.9 on 2025-12-05 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('costing', '0008_billofmaterial_batch_output_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='من تاريخ')),
                ('end_date', models.DateField(verbose_name='إلى تاريخ')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='إجمالي قيمة المشتريات')),
            ],
            options={
                'verbose_name': 'ملخص مشتريات',
                'verbose_name_plural': 'ملخصات المشتريات',
            },
        ),
        migrations.CreateModel(
            name='PurchaseSummaryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18, verbose_name='إجمالي الكمية المشتراة')),
                ('unit_cost', models.DecimalField(decimal_places=6, max_digits=18, verbose_name='تكلفة الشراء للوحدة')),
                ('line_total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=18, verbose_name='إجمالي الصنف')),
                ('purchase_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='costing.unit', verbose_name='وحدة الشراء')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='costing.rawmaterial', verbose_name='المادة الخام')),
                ('summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchases.purchasesummary', verbose_name='الملخّص')),
            ],
            options={
                'verbose_name': 'سطر ملخص مشتريات',
                'verbose_name_plural': 'سطور ملخص المشتريات',
            },
        ),
    ]
