# Generated by Django 5.2.9 on 2025-12-05 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_alter_period_options_remove_period_period_type_and_more'),
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasesummary',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='purchasesummary',
            name='start_date',
        ),
        migrations.AddField(
            model_name='purchasesummary',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_summaries', to='expenses.period', verbose_name='الفترة'),
        ),
    ]
