# Generated by Django 5.2.3 on 2025-12-25 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_remove_purchasesummary_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasesummaryline',
            name='last_unit_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='آخر سعر شراء'),
        ),
        migrations.AlterField(
            model_name='purchasesummaryline',
            name='quantity',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='إجمالي الكمية المشتراة'),
        ),
        migrations.AlterField(
            model_name='purchasesummaryline',
            name='unit_cost',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18, verbose_name='تكلفة الشراء للوحدة'),
        ),
    ]
