# Generated by Django 5.2.9 on 2025-12-06 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('costing', '0008_billofmaterial_batch_output_quantity_and_more'),
        ('expenses', '0004_alter_period_options_remove_period_period_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تعديل')),
                ('issue_date', models.DateField(verbose_name='تاريخ الحركة')),
                ('issue_type', models.CharField(choices=[('NON_SALES', 'منصرف لأغراض غير المبيعات'), ('ADJUSTMENT', 'تسوية/فاقد/هالك'), ('OTHER', 'أخرى')], default='NON_SALES', max_length=20, verbose_name='نوع الحركة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='expenses.period', verbose_name='الفترة')),
            ],
            options={
                'verbose_name': 'حركة صرف من المستودع',
                'verbose_name_plural': 'حركات صرف المستودع',
            },
        ),
        migrations.CreateModel(
            name='InventoryIssueLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تعديل')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=16, verbose_name='الكمية المنصرفة')),
                ('inventory_issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.inventoryissue', verbose_name='حركة الصرف')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='costing.rawmaterial', verbose_name='مادة خام')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='costing.unit', verbose_name='وحدة الصرف')),
            ],
            options={
                'verbose_name': 'بند صرف مستودع',
                'verbose_name_plural': 'بنود صرف المستودع',
            },
        ),
        migrations.CreateModel(
            name='StockCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تعديل')),
                ('type', models.CharField(choices=[('opening', 'جرد أول الفترة'), ('closing', 'جرد آخر الفترة')], max_length=20, verbose_name='نوع الجرد')),
                ('count_type', models.CharField(choices=[('opening', 'جرد أول المدة'), ('closing', 'جرد آخر المدة')], default='opening', max_length=20, verbose_name='نوع الجرد')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='expenses.period', verbose_name='الفترة')),
            ],
            options={
                'verbose_name': 'جرد مستودع',
                'verbose_name_plural': 'جرد المستودع',
                'unique_together': {('period', 'type')},
            },
        ),
        migrations.CreateModel(
            name='StockCountLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تعديل')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=16, verbose_name='الكمية المجردة')),
                ('raw_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='costing.rawmaterial', verbose_name='مادة خام')),
                ('semi_finished_product', models.ForeignKey(blank=True, help_text='منتج مكوّن يستخدم في الوصفات', null=True, on_delete=django.db.models.deletion.PROTECT, to='costing.product', verbose_name='منتج نصف مصنع')),
                ('stock_count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.stockcount', verbose_name='الجرد')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='costing.unit', verbose_name='وحدة الجرد')),
            ],
            options={
                'verbose_name': 'بند جرد',
                'verbose_name_plural': 'بنود الجرد',
            },
        ),
    ]
