# Generated by Django 5.2.9 on 2025-12-06 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockcount',
            name='count_type',
            field=models.CharField(choices=[('opening', 'Opening Balance'), ('closing', 'Closing Balance')], default='opening', max_length=10),
        ),
    ]
