# Generated by Django 5.2.9 on 2025-12-06 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_stockcount_count_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockcount',
            name='count_date',
            field=models.DateField(default='2025-01-01', verbose_name='تاريخ الجرد'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockcount',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات'),
        ),
        migrations.AlterField(
            model_name='stockcount',
            name='count_type',
            field=models.CharField(choices=[('opening', 'جرد أول الفترة'), ('closing', 'جرد آخر الفترة')], default='opening', max_length=10),
        ),
    ]
