# Generated by Django 5.2.9 on 2025-12-06 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_stockcount_count_date_stockcount_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockcount',
            name='notes',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='ملاحظات'),
        ),
    ]
