# Generated by Django 5.2.9 on 2025-12-06 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_stockcount_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockcountline',
            name='line_total_value',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True, verbose_name='إجمالي التكلفة المحفوظة'),
        ),
        migrations.AddField(
            model_name='stockcountline',
            name='saved_total_cost',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True, verbose_name='إجمالي تكلفة البند المحفوظة'),
        ),
        migrations.AddField(
            model_name='stockcountline',
            name='saved_unit_cost',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True, verbose_name='تكلفة الوحدة المحفوظة'),
        ),
        migrations.AddField(
            model_name='stockcountline',
            name='unit_cost_value',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True, verbose_name='تكلفة الوحدة المحفوظة'),
        ),
    ]
