# Generated by Django 5.2.9 on 2025-12-08 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_stockcountline_line_total_value_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BomTreeReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'تقرير شجرة المكونات (BOM Tree)',
                'verbose_name_plural': 'تقرير شجرة المكونات (BOM Tree)',
                'managed': False,
            },
        ),
    ]
