# Generated by Django 5.2.9 on 2025-12-24 12:28

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costing', '0010_billofmaterial_unit_cost_final'),
        ('inventory', '0006_bomtreereport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockcountline',
            name='line_total_value',
        ),
        migrations.AlterField(
            model_name='stockcountline',
            name='quantity',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=16, verbose_name='الكمية المجردة'),
        ),
        migrations.AlterField(
            model_name='stockcountline',
            name='unit_cost_value',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True, verbose_name='تكلفة الوحدة اليدوية (Opening)'),
        ),
        migrations.AddConstraint(
            model_name='stockcountline',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('raw_material__isnull', False), ('semi_finished_product__isnull', True)), models.Q(('raw_material__isnull', True), ('semi_finished_product__isnull', False)), _connector='OR'), name='stockcountline_exactly_one_item'),
        ),
    ]
