# Generated by Django 5.2.9 on 2025-12-24 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_remove_stockcountline_line_total_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockcount',
            name='is_committed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stockcount',
            name='is_submitted',
            field=models.BooleanField(default=False, verbose_name='تم الحفظ/الإقفال'),
        ),
    ]
