# Generated by Django 5.2.9 on 2025-12-24 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_stockcount_is_committed_stockcount_is_submitted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockcount',
            name='is_submitted',
        ),
        migrations.AddField(
            model_name='stockcount',
            name='committed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاعتماد'),
        ),
        migrations.AlterField(
            model_name='stockcount',
            name='is_committed',
            field=models.BooleanField(default=False, verbose_name='تم اعتماد الجرد'),
        ),
    ]
