# Generated by Django 5.2.9 on 2025-12-06 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryReports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='تقارير المخزون', max_length=100, verbose_name='الاسم')),
            ],
            options={
                'verbose_name': 'تقارير المخزون',
                'verbose_name_plural': 'تقارير المخزون',
            },
        ),
    ]
