# Generated by Django 5.2.9 on 2025-12-07 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryreports',
            options={'verbose_name': 'التقارير', 'verbose_name_plural': 'التقارير'},
        ),
        migrations.RemoveField(
            model_name='inventoryreports',
            name='name',
        ),
    ]
