# Generated by Django 5.2.9 on 2025-12-05 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('is_sellable', models.BooleanField(default=True)),
                ('is_semi_finished', models.BooleanField(default=False, help_text='مكوّن وسيط يدخل في مكونات منتج آخر')),
                ('selling_price_per_unit', models.DecimalField(blank=True, decimal_places=4, help_text='سعر بيع الوحدة الواحدة (إن وجد)', max_digits=12, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('quantity_in_base_per_purchase_unit', models.DecimalField(decimal_places=4, help_text='كم وحدة من الـ base_unit في كل purchase_unit (مثال: 3000 جرام في الكرتونة)', max_digits=12)),
                ('purchase_price_per_purchase_unit', models.DecimalField(decimal_places=4, help_text='سعر شراء العبوة (مثال: سعر الكرتونة)', max_digits=12)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BillOfMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boms', to='costing.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BOMItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=4, help_text='الكمية المطلوبة لكل وحدة من المنتج النهائي', max_digits=12)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='costing.billofmaterial')),
                ('component_product', models.ForeignKey(blank=True, help_text='لو المكوّن منتج نصف مصنع', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='component_in_boms', to='costing.product')),
                ('raw_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bom_items', to='costing.rawmaterial')),
            ],
            options={
                'verbose_name': 'BOM Item',
                'verbose_name_plural': 'BOM Items',
            },
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='base_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raw_materials_base', to='costing.unit'),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='purchase_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raw_materials_purchase', to='costing.unit'),
        ),
        migrations.AddField(
            model_name='product',
            name='base_unit',
            field=models.ForeignKey(help_text='وحدة بيع أو إنتاج المنتج (مثال: طبق، حبة، كيلو)', on_delete=django.db.models.deletion.PROTECT, to='costing.unit'),
        ),
    ]
