# Generated by Django 5.2.9 on 2025-12-05 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billofmaterial',
            options={'verbose_name': 'وصفة (BOM)', 'verbose_name_plural': 'الوصفات (BOMs)'},
        ),
        migrations.AlterModelOptions(
            name='bomitem',
            options={'verbose_name': 'عنصر في الوصفة', 'verbose_name_plural': 'عناصر الوصفة'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'منتج', 'verbose_name_plural': 'المنتجات'},
        ),
        migrations.AlterModelOptions(
            name='rawmaterial',
            options={'verbose_name': 'مادة خام', 'verbose_name_plural': 'المواد الخام'},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'verbose_name': 'وحدة قياس', 'verbose_name_plural': 'وحدات القياس'},
        ),
        migrations.AlterField(
            model_name='billofmaterial',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='billofmaterial',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعّالة'),
        ),
        migrations.AlterField(
            model_name='billofmaterial',
            name='name',
            field=models.CharField(blank=True, max_length=200, verbose_name='اسم الوصفة'),
        ),
        migrations.AlterField(
            model_name='billofmaterial',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boms', to='costing.product', verbose_name='المنتج'),
        ),
        migrations.AlterField(
            model_name='billofmaterial',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تعديل'),
        ),
        migrations.AlterField(
            model_name='bomitem',
            name='bom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='costing.billofmaterial', verbose_name='الوصفة'),
        ),
        migrations.AlterField(
            model_name='bomitem',
            name='component_product',
            field=models.ForeignKey(blank=True, help_text='لو المكوّن منتج نصف مصنع', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='component_in_boms', to='costing.product', verbose_name='منتج مكوّن (نصف مصنع)'),
        ),
        migrations.AlterField(
            model_name='bomitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='bomitem',
            name='quantity',
            field=models.DecimalField(decimal_places=4, help_text='الكمية المطلوبة من هذا المكوّن لإنتاج وحدة واحدة', max_digits=12, verbose_name='الكمية للوحدة الواحدة من المنتج'),
        ),
        migrations.AlterField(
            model_name='bomitem',
            name='raw_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bom_items', to='costing.rawmaterial', verbose_name='مادة خام'),
        ),
        migrations.AlterField(
            model_name='bomitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تعديل'),
        ),
        migrations.AlterField(
            model_name='product',
            name='base_unit',
            field=models.ForeignKey(help_text='مثل: طبق، حبة، كيلو', on_delete=django.db.models.deletion.PROTECT, to='costing.unit', verbose_name='وحدة المنتج (بيع/إنتاج)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='الكود'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_sellable',
            field=models.BooleanField(default=True, verbose_name='يُباع للعميل'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_semi_finished',
            field=models.BooleanField(default=False, help_text='يُستخدم كمكوّن في منتج آخر', verbose_name='منتج نصف مصنع'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, verbose_name='اسم المنتج'),
        ),
        migrations.AlterField(
            model_name='product',
            name='selling_price_per_unit',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='سعر بيع الوحدة'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تعديل'),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='base_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raw_materials_base', to='costing.unit', verbose_name='أصغر وحدة (أساس التكلفة)'),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='الكود'),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='name',
            field=models.CharField(max_length=200, verbose_name='اسم المادة الخام'),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='purchase_price_per_purchase_unit',
            field=models.DecimalField(decimal_places=4, help_text='سعر الكرتونة / الجالون / الشوال...', max_digits=12, verbose_name='سعر وحدة الشراء'),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='purchase_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raw_materials_purchase', to='costing.unit', verbose_name='وحدة الشراء'),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='quantity_in_base_per_purchase_unit',
            field=models.DecimalField(decimal_places=4, help_text='مثال: 3000 جرام في الكرتونة', max_digits=12, verbose_name='عدد الوحدات الأساسية في وحدة الشراء'),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تعديل'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=20, verbose_name='الاختصار'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(max_length=100, verbose_name='اسم الوحدة'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تعديل'),
        ),
    ]
