# Generated by Django 5.2.9 on 2025-12-05 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costing', '0002_alter_billofmaterial_options_alter_bomitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterial',
            name='cost_per_base_unit',
            field=models.DecimalField(blank=True, decimal_places=6, editable=False, help_text='تحسب تلقائياً من سعر الشراء ÷ عدد الوحدات الأساسية', max_digits=12, null=True, verbose_name='تكلفة أصغر وحدة'),
        ),
    ]
