# Generated by Django 5.2.9 on 2025-12-05 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costing', '0004_product_name_en_alter_product_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawmaterial',
            name='base_unit',
        ),
        migrations.RemoveField(
            model_name='rawmaterial',
            name='code',
        ),
        migrations.RemoveField(
            model_name='rawmaterial',
            name='cost_per_base_unit',
        ),
        migrations.RemoveField(
            model_name='rawmaterial',
            name='purchase_price_per_purchase_unit',
        ),
        migrations.RemoveField(
            model_name='rawmaterial',
            name='purchase_unit',
        ),
        migrations.RemoveField(
            model_name='rawmaterial',
            name='quantity_in_base_per_purchase_unit',
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='cost_per_ingredient_unit',
            field=models.DecimalField(blank=True, decimal_places=6, editable=False, max_digits=12, null=True, verbose_name='تكلفة وحدة الاستخدام'),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='ingredient_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='raw_materials_ingredient', to='costing.unit', verbose_name='وحدة الاستخدام في الوصفة'),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='purchase_price_per_storage_unit',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='سعر وحدة التخزين'),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='sku',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='كود المادة / SKU'),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='storage_to_ingredient_factor',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='عدد وحدات الاستخدام في وحدة التخزين'),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='storage_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='raw_materials_storage', to='costing.unit', verbose_name='وحدة التخزين'),
        ),
    ]
