# Generated by Django 5.2.9 on 2025-12-05 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costing', '0005_remove_rawmaterial_base_unit_remove_rawmaterial_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.AlterField(
            model_name='bomitem',
            name='quantity',
            field=models.DecimalField(decimal_places=4, max_digits=12, verbose_name='الكمية المطلوبة لإنتاج 1 وحدة من المنتج'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_semi_finished',
            field=models.BooleanField(default=True, help_text='يُستخدم كمكوّن في منتج آخر', verbose_name='منتج نصف مصنع'),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='ingredient_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='raw_materials_ingredient', to='costing.unit', verbose_name='وحدة الاستخدام'),
        ),
    ]
