# Generated by Django 5.2.9 on 2025-12-05 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costing', '0006_alter_product_options_alter_bomitem_quantity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'منتج', 'verbose_name_plural': 'المنتجات'},
        ),
        migrations.AlterField(
            model_name='bomitem',
            name='component_product',
            field=models.ForeignKey(blank=True, help_text='لو المكوّن منتج نصف مصنع أو منتج مطبوخ بكود', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='component_in_boms', to='costing.product', verbose_name='منتج مكوّن (نصف مصنع)'),
        ),
        migrations.AlterField(
            model_name='bomitem',
            name='quantity',
            field=models.DecimalField(decimal_places=4, help_text='الكمية من هذا المكوّن لكل وحدة من المنتج النهائي', max_digits=12, verbose_name='الكمية المطلوبة لإنتاج 1 وحدة من المنتج'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_semi_finished',
            field=models.BooleanField(default=False, help_text='يُستخدم كمكوّن في منتج آخر', verbose_name='منتج نصف مصنع'),
        ),
    ]
