# Generated by Django 5.2.9 on 2025-12-05 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costing', '0007_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billofmaterial',
            name='batch_output_quantity',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='مثال: 8000 جرام أو 30 طبق', max_digits=12, null=True, verbose_name='كمية الإنتاج الإجمالية'),
        ),
        migrations.AddField(
            model_name='billofmaterial',
            name='batch_output_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='costing.unit', verbose_name='وحدة كمية الإنتاج'),
        ),
        migrations.AlterField(
            model_name='bomitem',
            name='quantity',
            field=models.DecimalField(decimal_places=4, max_digits=12, verbose_name='الكمية المطلوبة لإنتاج 1 وحدة من المنتج'),
        ),
    ]
