# Generated by Django 5.2.9 on 2025-12-08 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costing', '0008_billofmaterial_batch_output_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billofmaterial',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True, verbose_name='تكلفة الوحدة الواحدة'),
        ),
    ]
