# Generated by Django 5.2.3 on 2025-12-09 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costing', '0009_billofmaterial_unit_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='billofmaterial',
            name='unit_cost_final',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True, verbose_name='تكلفة الوحدة (محفوظة)'),
        ),
    ]
