# Generated by Django 5.2.9 on 2025-12-05 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('costing', '0008_billofmaterial_batch_output_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(verbose_name='بداية الفترة')),
                ('period_end', models.DateField(verbose_name='نهاية الفترة')),
            ],
            options={
                'verbose_name': 'ملخص مبيعات',
                'verbose_name_plural': 'ملخصات المبيعات',
            },
        ),
        migrations.CreateModel(
            name='SalesSummaryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18, verbose_name='إجمالي الكمية المباعة')),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=18, verbose_name='سعر البيع للوحدة')),
                ('line_total', models.DecimalField(decimal_places=4, editable=False, max_digits=18, verbose_name='إجمالي الصنف')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='costing.product', verbose_name='المنتج')),
                ('summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.salessummary', verbose_name='الملخص')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='costing.unit', verbose_name='وحدة البيع')),
            ],
            options={
                'verbose_name': 'بند في ملخص المبيعات',
                'verbose_name_plural': 'بنود ملخص المبيعات',
            },
        ),
    ]
