# Generated by Django 5.2.9 on 2025-12-05 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salessummaryline',
            name='line_total',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=18, verbose_name='إجمالي الصنف'),
        ),
    ]
