# Generated by Django 5.2.9 on 2025-12-05 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_alter_period_options_remove_period_period_type_and_more'),
        ('sales', '0002_alter_salessummaryline_line_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salessummary',
            name='period_end',
        ),
        migrations.RemoveField(
            model_name='salessummary',
            name='period_start',
        ),
        migrations.AddField(
            model_name='salessummary',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_summaries', to='expenses.period', verbose_name='الفترة'),
        ),
    ]
