# Generated by Django 5.2.9 on 2025-12-06 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costing', '0008_billofmaterial_batch_output_quantity_and_more'),
        ('expenses', '0004_alter_period_options_remove_period_period_type_and_more'),
        ('sales', '0003_remove_salessummary_period_end_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesConsumptionSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('period', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='expenses.period', verbose_name='الفترة')),
            ],
            options={
                'verbose_name': 'تجميع استهلاك المواد',
                'verbose_name_plural': 'تجميعات استهلاك المواد',
            },
        ),
        migrations.CreateModel(
            name='SalesConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_sold', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='الكمية المباعة')),
                ('quantity_consumed', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='الكمية المستهلكة')),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='تكلفة وحدة المادة')),
                ('total_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='إجمالي التكلفة')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='costing.product', verbose_name='المنتج')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='costing.rawmaterial', verbose_name='المادة الخام')),
                ('summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.salesconsumptionsummary', verbose_name='تجميع')),
            ],
        ),
    ]
