# Generated by Django 5.2.9 on 2025-12-06 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costing', '0008_billofmaterial_batch_output_quantity_and_more'),
        ('sales', '0004_salesconsumptionsummary_salesconsumption'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesconsumption',
            name='semi_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consumption_as_component', to='costing.product', verbose_name='منتج نصف مصنع'),
        ),
        migrations.AlterField(
            model_name='salesconsumption',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumption_as_final_product', to='costing.product', verbose_name='المنتج النهائي'),
        ),
        migrations.AlterField(
            model_name='salesconsumption',
            name='raw_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='costing.rawmaterial', verbose_name='مادة خام'),
        ),
    ]
