# Generated by Django 5.2.9 on 2025-12-06 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costing', '0008_billofmaterial_batch_output_quantity_and_more'),
        ('sales', '0005_salesconsumption_semi_product_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesconsumption',
            options={'verbose_name': 'استهلاك مادة خام', 'verbose_name_plural': 'استهلاك المواد الخام'},
        ),
        migrations.RemoveField(
            model_name='salesconsumption',
            name='semi_product',
        ),
        migrations.AddField(
            model_name='salesconsumption',
            name='level',
            field=models.PositiveIntegerField(default=1, verbose_name='مستوى التفكيك'),
        ),
        migrations.AddField(
            model_name='salesconsumption',
            name='source_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consumption_sources', to='costing.product', verbose_name='المصدر'),
        ),
        migrations.AddField(
            model_name='salesconsumption',
            name='source_type',
            field=models.CharField(blank=True, choices=[('final', 'منتج نهائي'), ('semi', 'منتج نصف مصنع')], max_length=10, null=True, verbose_name='نوع المصدر'),
        ),
        migrations.AlterField(
            model_name='salesconsumption',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='costing.product', verbose_name='المنتج النهائي'),
        ),
        migrations.AlterField(
            model_name='salesconsumption',
            name='raw_material',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to='costing.rawmaterial',
                verbose_name='المادة الخام',
                null=True,
                blank=True,
            ),
        ),

    ]
