# Generated by Django 5.2.9 on 2025-12-08 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costing', '0009_billofmaterial_unit_cost'),
        ('sales', '0006_alter_salesconsumption_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesconsumption',
            name='raw_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_consumptions', to='costing.rawmaterial', verbose_name='المادة الخام'),
        ),
    ]
