# Generated by Django 5.2.9 on 2025-12-11 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_alter_salesconsumption_raw_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesconsumption',
            name='quantity_consumed',
            field=models.DecimalField(decimal_places=6, max_digits=18, verbose_name='الكمية المستهلكة'),
        ),
        migrations.AlterField(
            model_name='salesconsumption',
            name='quantity_sold',
            field=models.DecimalField(decimal_places=4, max_digits=18, verbose_name='الكمية المباعة'),
        ),
        migrations.AlterField(
            model_name='salesconsumption',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name='إجمالي التكلفة'),
        ),
        migrations.AlterField(
            model_name='salesconsumption',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name='تكلفة وحدة المادة'),
        ),
    ]
