# Generated by Django 5.2.9 on 2025-12-22 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_alter_salesconsumption_quantity_consumed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesconsumption',
            name='quantity_consumed',
            field=models.DecimalField(decimal_places=6, max_digits=18, verbose_name='الكمية المستهلكة (وحدة الاستخدام)'),
        ),
        migrations.AlterField(
            model_name='salesconsumption',
            name='quantity_sold',
            field=models.DecimalField(decimal_places=4, max_digits=18, verbose_name='الكمية المباعة من المنتج النهائي'),
        ),
        migrations.AlterField(
            model_name='salesconsumption',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name='تكلفة وحدة المادة (وحدة الاستخدام)'),
        ),
    ]
